### ISSUE TITLE
Collect use cases from bad data/real world data to decide what needs to be supported in pond/pypond

### ISSUE THREAD

**Issue by jdugan1024** [esnet/pypond#3] opened 2016-07-13 20:49 UTC
As @jdugan1024 works with pond on the server side what features do we need, etc?

---
Collected tasks:
 - [x] aggregation function cleaning strategies
 - [x] timeseries.fill() to fix missing values in a TimeSeries
 - [x] reindexing to add missing rows. This might be `align`.
 - [x] ability to change meta data, e.g. renameColumns()
 - [x] add percentile and quantile functions to python code

**Comment by montegoode** [comment] 2016-07-14 14:22
Assigning this to myself to implement what Jon needs, and commenting to test Slack integration.

**Comment by jdugan1024** [comment] 2016-07-22 19:41
When dealing with data from the "real world" it is often dirty. How can pond help with this?

I run into the missing data and columns of varying lengths in the portal when dealing with OSCARS data. The way the counters are reported for OSCARS I have to sum 4 values to get the value we want to show. Sometimes I will having missing data (as Nones) in one of the columns and sometimes I will see the case where one or more of the columns has less data points than the other.  

## Columns in a time series have a differing number of rows.  

This can happen at input time, I don't think we can make any good assumptions about how to interpret input data with columns of differing lengths. I think we should probably insist that columns are the same length, especially if we are going to perform an aggregation on them. Do we want to enforce this kind of thing?  

I haven't tested this yet, so maybe we already do enforce this? I'm guessing we do implicitly since each row is bundled into an Event object which holds all the columns for that row.

## Missing data

Sometimes we don't have a measurement for a particular timestamp. In many cases this is reported as a None for that column.  Note that None is different than 0.  0 means have a measurement and it is 0 while None means we don't have a measurement.  For operations that don't combine columns, I think it is OK to leave this as a None. The downstream code should know that None means no measurement and do what it deems correct.

I'm not sure that clean as implemented is quite what we want to do.  It does simplify some things but it seems that it has potential for surprise with aggregation functions. If you clean a collection the events in the collection depends on which columns you used in the clean.  That is, if you clean on a column that has a None, it deletes the entire event. If you clean the same collection on a column that has no Nones you end up with a all of events still, even though some of them have None in a different column.  This isn't really a problem until you try to apply an aggregate, when sum will choke on [1, 2, None] or whatever. 

### Missing Data: Option 1

One approach would be to change clean a little bit. Clean would give three options for Events with Nones in one or more columns:

1. Replace the Nones (and possibly NaNs as well) with a 0
2. Remove the Event from the collection

I wonder if it would be good to either default to cleaning on all columns since it would be easy to shoot yourself in the foot by cleaning on some columns and the doing an aggregate on other columns.

The one downside to this approach is that we lose the explicit Nones so it's harder know there is missing data, you'd need to look at the timestamps -- and if the timestamps aren't uniform it's pretty much impossible. I like the simplicity of this approach, but this might be a deal breaker.

### Missing Data: Option 2

What should you do when you sum two columns and some of the values in one of the columns is None. Should the sum return None or should it return the sum replacing None with a 0?  I think we want to let the user decide what to do with aggregation a missing data. Basically some kind of flag for the built in aggregates to select whether to map missing data to some value (usually 0) or to propagate the None to the aggregate. This probably works out to writing wrappers around the function (say sum) to deal with these cases.  aggregate can possibly just pass this down as an optional keyword argument, such as `missing_strategy` or something.

The aggregate documentation should call attention to this issue and encourage the the user to consider this when they implement their own aggregation functions.

This is more complicated, but allows aggregates to contain explicit information about missing data points.

## NaN vs None

The semantics seem a little different to me: None means missing data and NaN means there was a math operation that produced a NaN result.  However, I'm wondering if we should just treat them both as missing data. We should decide on something and document it and the above discussion on Missing Data should take this into account.

**Comment by jdugan1024** [comment] 2016-07-22 20:33
Might be nice if TimeSeries, Collection and Event implemented things like __len__ and __iter__.  Would make some things more idiomatic.

**Comment by jdugan1024** [comment] 2016-07-22 22:16
Couple of things I keep running into, not sure there is a good solution, but in order to rename columns I end up doing:

```
raw_series = series.to_json()
raw_series.columns = ['new', 'names']
return TimeSeries(raw_series)
```

Seems to be similar for modifying metadata.  Since the column names propagate all the way into the Events I can see that renaming columns might be a bit fiddly.  However, seems like updating metadata should be allowed.

**Comment by jdugan1024** [comment] 2016-07-22 23:25
One example, for adding up a group of interfaces I ended up with this, which was bit more awkward than I wanted.  Probably I'm doing it wrong.

```python
        def event_none_sum(events, field_spec):
            """Sum function that uses 0 for Nones."""
            def none_sum(points):
                total = 0
                for point in points:
                    if point:
                        total += point

                return total

            summ = Event.combine(events, field_spec, none_sum)
            return summ[0] if summ else None

        traffic = TimeSeries.timeseries_list_reduce({"labels": labels},
                                                    series_list,
                                                    event_none_sum,
                                                    ["in", "out"])

```

**Comment by montegoode** [comment] 2016-07-26 15:20
@jdugan1024 Some comments on the missing data stuff:

### Clean

I see where you're going with that. I propose that we leave `.clean()` as it is and introduce a new method called something like `.pad()` or `.fill()`. I would envision this method as taking an argument (defaulting to 0?) and returning a new collection where any `None` values have been converted to whatever that arg was across all columns.

( cc: @pjm17971 as this is API design, what do you think of that? )

### Sum variations

One can already handle this issue on a per-case basis. All sum is is a wrapper around `Collection.aggregate()` - to wit:

```
    def sum(self, field_spec=None):
        """Get sum

        Parameters
        ----------
        field_spec : str, list, tuple, None
            Column or columns to look up. If you need to retrieve multiple deep
            nested values that ['can.be', 'done.with', 'this.notation'].
            A single deep value with a string.like.this.  If None, all columns
            will be operated on.

        Returns
        -------
        int or float
            Summed value.
        """
        return self.aggregate(Functions.sum, field_spec)
```

Sum is just a function passed to `.aggregate()` - one could roll their own to handle the summing however they wish. This can also be accessed by `TimeSeries.aggregate()` which just talks to the underlying collection.

### None and NaN

We are already treating None and NaN as missing data in these cases.

**Comment by montegoode** [comment] 2016-07-26 18:09
@jdugan1024 passing a function like this to `TimeSeries.aggregate()`:

```
    def sum(values):
        for i in enumerate(values):
            if i[1] is None:
                values[i[0]] = 0
        return reduce(lambda x, y: x + y, values, 0)
```

Would do the trick and would be a little less clunky.

**Comment by montegoode** [comment] 2016-07-26 18:30
@jdugan1024 As far as the renaming columns thing goes...a couple of things:

1) Thats not merely a simple matter of updating the metadata. When you call `to_json()` the column list is generated by asking the underlying events "what columns do you contain?" That isn't metadata that exists at the `TimeSeries` level. 

2) I would argue that having that kind of decoupling between what the `TimeSeries` thinks it contains, and what the `Event` objects actually contain, is asking for all kinds of pain. Plus using the right column names is the way that the points are rendered out of the events into the wire format with the correct alignment.

Part of the reason of using the immutable objects is so we don't end up with weird side effects like that could potentially cause.

**Comment by pjm17971** [comment] 2016-07-26 18:45
I think all bets are off if you reach into the internal structure of the objects. There's some hope that this will result in a new object. i.e. you'll be holding onto a changed object rather than the original. So I think anytime there's the need to use _collection or whatever else within the object, you are going against the public API and a flirting with pain. But I think the suggestion here is that renaming a column would be helpful, which would in fact mean modifying all the events in the TimeSeries to create new Events and then returning a new TimeSeries. Seems like that's just a specialization of the TimeSeries.collapse() function.

**Comment by montegoode** [comment] 2016-07-26 18:58
What Peter said. Or more succinctly: that renaming the columns results in a new time series containing new event objects is by design. 

And yeah, using `.collapse()` would be the cleanest way of doing it. I can whip up an example.

**Comment by pjm17971** [comment] 2016-07-26 19:05
**Cleaning:**

note: for this discussion, I'm calling a NaN, null, or undefined (in JS), or NaN or None (in Python).

For the clean stuff, I think there's two main places we need to consider missing values:
 1. How to treat aggregations on value lists that contain missing values.
 2. How to process a TimeSeries to address missing values

**aggregations**

My initial thoughts on this, without having fully implemented anything, is to deal with the aggregation case in the aggregation functions themselves (sum(), avg(), etc). In my current branch, these functions now need to be specified as `sum()` rather than `sum`, and they themselves return a function that acts on a valuelist. (i.e. they use closures). My proposal is to allow the user to pass in one of 4 functions into this as the cleaning strategy:
 * keepMissing = values => values;
 * ignoreMissing = values => values.filter(isValid);
 * zeroMissing = values => values.map(v => isValid(v) ? v : 0);
 * propagateMissing = values => ignoreMissing(values).length === values.length ? values : null;
Or something like that.

`keepMissing` takes a list of values and returns the list. This is the noop version of cleaning. 
`ignoreMissing` filters our the missing values.
`zeroMissing` sets missing values to 0.
`propagateMissing` means that if there's a missing value is the aggregation valuelist then the result of the aggregation is null itself.

The "correct" thing to do is up to the user, but I think the best default is to filter out the missing values. But we might say that a sum() is null if there's a missing value.

For functions that wrap an aggregation we'd need the clean strategy to be passed through to the aggregation function, unless there's only one strategy that makes any sense (I don't know if this is the case anywhere).

**filling**

This is the case where you have a raw TimeSeries and you want to heal missing values. I think you want to be able to do a couple of things:
 1. Filter out events with missing values in a fieldSpec - this is just a specialized filter operation
 2. Replace missing values with a new value

In the case of the second function, probably `fill()`, there's several ways to replace missing values. We need to decide what the minimum set is to be useful to us, initially. Possibilities are:
 * fill with 0
 * fill with previous non-missing value
 * interpolate between non-missing values, based on timestamp
For each of these it would be useful to supply a limit. A limit of 2 would fill two missing values only. This is because we often want to patch small holes in TimeSeries, but if there's a substantial hole it makes sense sometimes (e.g. visualization), to keep it as missing data. If we missed an hour of data it should show that.

**Comment by montegoode** [comment] 2016-07-26 19:05
Yeah, `.collapse()` can only do one column at a time. I would need to write something that would do essentially the same thing but could rename multiple columns if we want to do it all in one throw rather than calling `.collapse()` multiple times.

**Comment by pjm17971** [comment] 2016-07-26 19:09
Is the proposal then to have something like `ts.renameColumns(["in", "out"], ["new_in", "new_out"])`? I'm ok with that. It's probably good to be able to enable multiple columns here, because it will have to rebuild all the events.

**Comment by montegoode** [comment] 2016-07-26 19:12
We could so it multiple ways. I might prefer something like this since it's easier to keep track of:

```
ts.rename_columns({'in': 'new_in', 'out': 'new_out'})
```

**Comment by montegoode** [comment] 2016-07-26 19:37
I like the idea of letting the aggregation functions take care of the filtering and that would also provide some building blocks for users to use as well.

I think I get your drift, I'm going to start prototyping something in python as an example to make sure we're on the same page.

**Comment by pjm17971** [comment] 2016-07-26 19:42
When I played with the aggregation side of things last night, I ended up with my aggregation functions looking like this:
```
export function sum(clean = ignoreMissing) {
    return function(values) {
        const cleanValues = clean(values);
        if (!cleanValues) return null;
        return _.reduce(cleanValues, (a, b) => a + b, 0);
    }
}
```
there might be a nicer way to write that, but that's the gist.

**Comment by montegoode** [comment] 2016-07-26 20:10
Like this?

```
#!/usr/bin/env python

"""
Prototype for new style filtered aggregation functions.
"""

from functools import reduce


class Filters(object):
    """Filter functions to pass to aggregation function factory."""
    @staticmethod
    def keep_missing(events):
        """no-op"""
        return events

    @staticmethod
    def ignore_missing(events):
        """just pull out the bad values."""
        good = list()

        for i in events:
            if i is not None:
                good.append(i)

        return good

    @staticmethod
    def zero_missing(events):
        """make bad values 0"""
        filled = list()

        for i in events:
            if i is None:
                filled.append(0)
            else:
                filled.append(i)

        return filled

    @staticmethod
    def propogate_missing(events):
        """it's all bad if there are missing values."""
        for i in events:
            if i is None:
                return None

        return events


class Functions(object):
    """new style functions."""

    @staticmethod
    def sum(flt=Filters.keep_missing):
        """sum with appropriate filter."""

        def in_sum(values):
            """return the sum with the applied filter."""
            vals = flt(values)

            if vals is None:
                return None

            return reduce(lambda x, y: x + y, vals, 0)

        return in_sum

    @staticmethod
    def avg(flt=Filters.keep_missing):
        """avg with appropriate filter."""

        def in_avg(values):
            """return the average with applied filter."""
            vals = flt(values)

            if vals is None:
                return None

            return float(Functions.sum()(vals)) / len(vals)

        return in_avg


def main():
    """execute."""

    values = [1, 2, 3]
    bad_values = [1, 5, None]

    plain_sum = Functions.sum()    # keep_missing is the default
    print(plain_sum(values))       # yields 6

    prop_sum = Functions.sum(Filters.propogate_missing)
    print(prop_sum(values))        # yields 6
    print(prop_sum(bad_values))    # yields None

    ignore_avg = Functions.avg(Filters.ignore_missing)
    print(ignore_avg(values))      # yields 2
    print(ignore_avg(bad_values))  # yields 3

    zero_avg = Functions.avg(Filters.zero_missing)
    print(zero_avg(values))        # yields 2
    print(zero_avg(bad_values))    # yields 2 as well

if __name__ == '__main__':
    main()

```

**Comment by pjm17971** [comment] 2016-07-26 20:12
Yep, I think that looks exactly right.

**Comment by montegoode** [comment] 2016-07-26 20:23
So what I get from all this is that there are three things on deck for the next branch/releases of both the javascript and python versions:

1. Modify the aggregation functions to return a function and do filtering as just discussed.
2. Add a `.rename_columns()` method to all of the `Event` objects - it will function similarly to `Event.collapse()` in that it will return a new event. Will this be on all of the event classes or just on `Event` like collapse is?
3. Add the `.fill()` method to the `TimeSeries` and `Collection` objects to cleanse bad values and return new data structures.

And for the python code: add in the idiomatic meta class methods like `__len__` and `__iter__`.

Is this right?

**Comment by pjm17971** [comment] 2016-07-26 20:27
Yeah. I've added those tasks to the top of this item. We probably should make JS and Python Issues to track and link from here to keep track of them.

I addition, I've added a percentile and quantile function. Some portal visualization stuff needs it. I'd have to look at my checkins to see if anything else is in my next release branch, but that's the main stuff for pond.

**Comment by montegoode** [comment] 2016-07-26 21:10
Also, in the python code currently, I consider python `None`, an empty string or an actual NaN all to be non-values. Just documenting that here.

**Comment by montegoode** [comment] 2016-07-28 14:58
### Proposal on filtering args

Per a Slack discussion between @pjm17971 and myself about how to handle passing filtering functions to the higher level aggregation methods (`TimeSeries.sum()`, et al). We rejected the notion of setting a filter as a piece of state in a class instance in favor of adding a new arg to the existing methods. Those methods already take `field_spec` as an optional arg. This means that if the user wants to set a filter, but not a spec, they will need to do it as apropos for the lang (explicit python keyword arg, javascript positional args). This was found to be acceptable.

So I wanted to come up with an interface that will:

1. Be consistent with our current practice of letting the `field_spec` default to `None` in method prototypes and setting the default value dynamically in a single place (as opposed to setting a bunch of defaults throughout the code. I think this is important.
2. Which will make it easy to change the default at a later date if need be.
3. Future-proof us in case we decide to do something like providing a mechanism by which a user could globally set a default of their choosing. There are no plans to do this now, but that's what future proofing is all about.
4. Allow for the validation of input.
5. Keep the modified code clean.

### Single processing point

In python source, the four filtering methods are static methods in `pypond.functions.Filters`. So I would add the following constant and function to the `functions` module:

```
FILTER_NAMES = [x[0] for x in inspect.getmembers(Filters, predicate=inspect.isfunction)]


def f_check(flt):
    """Set the default filter for aggregation operations when no
    filter is specified. When one is, make sure that it is a
    valid filter.
    """

    # default case when no filter is specified to a higher
    # level aggregation method.
    if flt is None:
        return Filters.keep_missing

    # are we legit?
    if not callable(flt) or flt.__name__ not in FILTER_NAMES:
        msg = 'Invalid filter: expected a method from pypond.functions.Filters'
        raise FilterException(msg)

    # we are legit
    return flt
```
This will handle setting the default and we could add more logic to it at a later date if need be.

### Method implementation

And here is how it would look implemented in the code:

```
    def sum(self, field_spec=None, filter=None):
        return self.aggregate(Functions.sum(f_check(filter)), field_spec)
```
This will be a sweeping enough change that I want to keep the changes to the "actual code" as minimal and clean as possible while isolating the rest of the logic all in one place. Something similar could be implemented in the JavaScript codebase as appropriate.

**Comment by montegoode** [comment] 2016-07-28 20:03
### Outstanding questions

@pjm17971 :  Got a few questions/clarifications about some of the tasks before I press on with the rest of the features:

1. Since column renaming was compared to `.collapse()`, are we implementing column renaming on all event variants, or only on `Event` like collapse does. I am guessing that we want it for all event types.
2. Corollary to above - do we want that implemented as a simple method like `Event.collapse()` or should I whip up a `Renamer` processor and implement it as a pipeline situation? I am also guessing we want this.
3. RE: `TimeSeries.fill()` does this need to operate on an actual `field_spec` or should/can it just act "globally" on all values in all events in the series? it seems like we don't need a the field spec level of granularity because `TimeSeries.clean()` already offers that.
4. How would the proposed `.align()` method work?

**Comment by pjm17971** [comment] 2016-08-01 17:22
@montegoode:
1) Yes, I think all functions eventually should support all Event types seamlessly. I know they don't all do it yet.
2) At the event level, I'd think Pipeline.Map is pretty much all that's needed. So I wouldn't worry about it.
3) I was thinking this too, but I think actually we need control over what columns to fill. Fill is a little different than clean (though having the two functions is now a little confusing), since it will either use the previous value, or zero, and have a limit to how much it will fill. There's other strategies that might be useful to add later as well. Ideally I think clean should be replaced, but I haven't thought about that too much.

4. Align: this is basically the binning that esmond does, but without the derivative.

So, in a pipeline processor, you'd grab the first event and call that `prev`. Then when the next event comes in (call it `current`), if it's across a time boundary (like "5m") from the `prev` event, you'd interpolate a new event that's on the 5m boundary. Interpolation options are `linear` or `hold`. i.e. use both values or just the previous value. `linear` would be the default.

If `current` is not across a boundary (i.e. within the same 5m window as `prev`, it becomes the `prev`.

If `current` is multiple boundaries away from `prev`, you'd interpolate all Events for the intermediate boundaries and so emit multiple events. I think we want a `limit` option on this too, so if there are greater than `limit` boundaries between the incoming Events then I think the correct thing to do is still emit Events between the incoming Events on the boundaries, but with value null. This aligns the data, but stops outages etc from being interpolated across large gaps. But for short gaps we can fill in the missing values as we align. Sometimes it's just aliasing that causes a span of more than one window, in which case we'd want to fill for sure. While if it's really a chunk of missing data, that should be reflected in the alignment. 

Note that you should be able to combine an alignment with a derivative eventually to do what esmond does with incoming counter values.

A target use for this is the dataflow still Melissa is doing (cc @melstockman ) because Pond has tests etc, I would imagine if we can use this for some of the batch and (eventually stream processing) work she's doing, that would be awesome.

Also, you should be able to align a timeseries. (But not a collection, since it's a time sequence based operation.) I'd guess this would just be a wrapper for a pipeline.

**Comment by montegoode** [comment] 2016-09-07 20:44
Finished with PR: https://github.com/esnet/pypond/pull/8

Also with some optimizations.

**Closed by montegoode** 2016-09-07 20:44 UTC
